ALTER TABLE fichefrais 
ADD COLUMN ARCHIVED BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE lignefraisforfait 
ADD COLUMN ARCHIVED BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE visiteur 
ADD COLUMN ARCHIVED BOOLEAN NOT NULL DEFAULT FALSE;